name = "gohighlevel-mcp-proxy"
main = "cloudflare-worker.js"
compatibility_date = "2024-01-01"

[env.production]
name = "gohighlevel-mcp-proxy"
route = "ghl-mcp.your-domain.com/*"

[env.production.vars]
VERCEL_URL = "https://gohighlevel-mcp-server-9ja5gnnww-vuplicity.vercel.app"
